Sort all imports across .py files
cat-dev-group/bot-py pull request #73
Opened 2021-07-09 01:17 UTC by Objectivitix

In alphabetical order, imports should be separated into three groups:

1. stdlibs
2. third-party
3. local applications 

However, our current code has lots of inconsistencies with this order. This PR fixes them all.

2021-07-09 01:21 UTC, Kronifer approved these changes
Our imports dont suck now

2021-07-09 02:04 UTC, dawnofmidnight requested changes
Before we take into account anything else, imports without a from (`import package`) should be above those with a from (`from package import x`).

2021-07-09 02:45 UTC, Objectivitix commented
@dawnofmidnight where did you see that? I specifically searched for this issue (ordering with froms) and found no corresponding rule in PEP8

2021-09-12 14:31 UTC, dawnofmidnight commented
All issues and PRs are being closed as this repository is in the process of archival. All future development on the catbot will occur at [cat-dev-group/bot](https://github.com/cat-dev-group/bot).

2021-09-12 14:31 UTC, closed without merging